---
title: "SVM"
author: "Gerrit"
date: "26.03.2015"
output: html_document
---

SVM
===

More pictures than results this time.

Linear SVM classifier
---------------------

Generate data in two dimensions

```{r}
set.seed(10111)
x = matrix(rnorm(40), 20, 2)
y = rep(c(-1,1), c(10,10))
x[y==1,] = x[y==1,]+1
plot(x, col = y+3, pch = 19)
```

The package `e1071` contains the svm function. The name comes from a room number on the TU Berlin (really TU...).

```{r}
library(e1071)
dat = data.frame(x, y = as.factor(y))
svm.fit = svm(y ~ ., data = dat, kernel = "linear", cost = 10, scale = FALSE)
print(svm.fit)
plot(svm.fit, dat)
```

```{r}
make.grid = function(x, n = 75) {
  grange = apply(x, 2, range)
  x1 = seq(from = grange[1,1], to = grange[2,1], length = n)
  x2 = seq(from = grange[1,2], to = grange[2,2], length = n)
  expand.grid(X1 = x1, X2 = x2)
}

xgrid = make.grid(x)
ygrid = predict(svm.fit, xgrid)
plot(xgrid, col = c("red", "blue")[as.numeric(ygrid)], pch = 20, cex = .2)
points(x, col = y+3, pch = 19)
points(x[svm.fit$index,], pch = 5, cex = 2)
```

To obtain the linear coefficients some work is needed.

```{r}
beta = drop(t(svm.fit$coefs)%*%x[svm.fit$index,])
beta0 = svm.fit$rho
plot(xgrid, col = c("red", "blue")[as.numeric(ygrid)], pch = 20, cex = .2)
points(x, col = y + 3, pch = 19)
points(x[svm.fit$index,], pch = 5, cex = 2)
abline(beta0 / beta[2], -beta[1] / beta[2], lty = 2)
abline((beta0-1)/beta[2], -beta[1] / beta[2], lty = 2)
abline((beta0+1)/beta[2], -beta[1] / beta[2], lty = 2)
```


Nonlinear SVM
-------------

```{r}
load(url("http://statweb.stanford.edu/~tibs/ElemStatLearn/datasets/ESL.mixture.rda"))
names(ESL.mixture)
# rm(x,y)
attach(ESL.mixture)
```

These data are also 2-dimensionsal. Lets plot and fit a nonlinear SVM with radial kernel.

```{r}
plot(x, col=y+1)
dat = data.frame(y = factor(y), x)
fit = svm(factor(y) ~ ., data = data, scale = FALSE, kernel = "radial", cost = 5)
```

```{r}
xgrid = expand.grid(X1 = px1, X2 = px2)
ygrid = predict(fit, xgrid)
plot(xgrid, col = as.numeric(ygrid), pch = 20, cex = .2)
points(x, col = y + 1, pch = 19)
```

```{r}
func = predict(fit, xgrid, decision.values = TRUE)
func = attributes(func)$decision
xgrid = expand.grid(X1 = px1, X2 = px2)
ygrid = predict(fit, xgrid)
plot(xgrid, col = as.numeric(ygrid), pch = 20, cex = .2)
points(x, col = y+1, pch = 19)

contour(px1, px2, matrix(func, 69, 99), level = 0, add = TRUE)
contour(px1, px2, matrix(prob, 69, 99), level = .5, add = TRUE, col = "blue")
```

